### ISSUE TITLE
Outlook.com Ads not being Blocked even with Brave Shields set to "Aggressive Mode"

### ISSUE THREAD

**Issue by DesertBear** [brave/adblock-lists#1111]
**Description:**
Ads are not being blocked on outlook.com, even with Brave Shields set to "Aggressive" and "Fanboy Annoyances List" and "uBlock Annoyances List" enabled as well.

They are blocked when the view is set to _Roomy_, however, they are not blocked when the view is set to _Cozy_ or _Compact_.

uBlock Origin tries to block them, however still displays a grey box instead of removing it.

**Steps to Reproduce:**
**1)** Go to `brave://settings/shields` and set "Trackers & ads blocking" to "Aggressive".

**2)** Go to `brave://settings/shields/filters` and enable "Fanboy Annoyances List" and "uBlock Annoyances List".

**3)** Sign in to https://outlook.live.com/mail/0/

**4)** Observe the top of the inbox.

**Actual result:**
Ads are not being blocked.

_Screenshot A:_
![Screenshot A](https://user-images.githubusercontent.com/27423064/226208848-3be52a02-bed7-4ead-bcf9-4a7bcb50110a.png)

_Screenshot B:_
![Screenshot B](https://user-images.githubusercontent.com/27423064/226208853-e0ad7ae3-71b6-4042-a3ce-dc17152f4d54.png)

_Screenshot C:_
![Screenshot C](https://user-images.githubusercontent.com/27423064/226208855-665c3555-b339-478d-bbac-5ba631fa766d.png)

_Screenshot D:_
![Screenshot D](https://user-images.githubusercontent.com/27423064/226208861-3ff83493-0eaf-4be1-8769-6047a9acce92.png)

**Expected result:**
The Ads should be blocked and placeholders removed.

_Screenshot E:_
![Screenshot E](https://user-images.githubusercontent.com/27423064/226208866-eefd4eb7-63c7-4667-bd69-cb02bc70583f.png)

_Screenshot F:_
![Screenshot F](https://user-images.githubusercontent.com/27423064/226208871-3adc4771-5728-4845-9532-ba644c12239b.png)

**Brave version (brave://version info):**
```
Brave:    1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit) 
Revision: c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS:       Windows 10 Version 22H2 (Build 19045.2728)
```

**Comment by antonok-edm** [comment]
@DesertBear with Aggressive mode enabled, it should be fixed in Beta - can you try 1.50.x?

**Comment by DesertBear** [comment]
For some reason I though the adblock improvements were already added to 1.49 Stable.

In 1.50 Beta, the ad text no longer appears.  Although it still shows the grey box, as the EasyList cosmetic filter needs modifying.

**Comment by antonok-edm** [comment]
> For some reason I though the adblock improvements were already added to 1.49 Stable.

`:has` is supported in 1.49, but I think the specific filter targeting those elements uses `-abp-has` which is supported in 1.50.

> it still shows the grey box, as the EasyList cosmetic filter needs modifying

cc @ryanbr

**Comment by ryanbr** [comment]
Initial test, not seeing any empty space here. Signed up to some newsletters to try to force some adverts also. (Tested in Brave Beta 1.50.101)

![outlook-test](https://user-images.githubusercontent.com/1659004/227517806-22a46b91-a8d9-416d-955a-c4430fdc9106.jpg)

**Comment by DesertBear** [comment]
@ryanbr 

Your screenshots are only showing the view set to "_Roomy_".  Did you try it with "_Cozy_" and "_Compact_" as per the original post?

Your second screenshot is also on the Focused tab.

The below screenshots are from Brave Beta 1.50.102, where the issue is still present.

```
Brave:    1.50.102 Chromium: 111.0.5563.116 (Official Build) beta (64-bit) 
Revision: ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS:       Windows 10 Version 2004 (Build 19041.2728)
```

**_1) Right Reading Pane, Focused Inbox Off:_**
![Screenshot A](https://user-images.githubusercontent.com/27423064/227776535-4951498f-b856-4257-a0f4-94fdd64af53f.png)

![Screenshot B](https://user-images.githubusercontent.com/27423064/227776543-c0688ca4-0051-47d6-9850-3b19aa8972a9.png)

![Screenshot C](https://user-images.githubusercontent.com/27423064/227776548-04e22e6c-c53e-4646-b219-b3d876defafe.png)

**_2) Right Reading Pane, Focused Inbox On:_**
![Screenshot D](https://user-images.githubusercontent.com/27423064/227776554-6cdd0203-8a3d-4a55-ba9b-25e2fd07ec01.png)

![Screenshot E](https://user-images.githubusercontent.com/27423064/227776563-73f8b38e-7289-44d0-a400-9a67dd8f848a.png)

![Screenshot F](https://user-images.githubusercontent.com/27423064/227776567-1391aeca-ec76-4820-be51-537a04bc4530.png)

**_3) Bottom Reading Pane, Focused Inbox Off:_**
![Screenshot G](https://user-images.githubusercontent.com/27423064/227776574-111c35c1-713a-4ebe-b721-17a2cae46e5c.png)

![Screenshot H](https://user-images.githubusercontent.com/27423064/227776579-60452958-386a-4fec-89aa-cb1664079d8a.png)

![Screenshot I](https://user-images.githubusercontent.com/27423064/227776585-905a3dcd-6296-40da-9f2f-567cf526ef22.png)

**_4) Bottom Reading Pane, Focused Inbox On:_**
![Screenshot J](https://user-images.githubusercontent.com/27423064/227776594-a031cfbd-d93b-440d-983d-b99ff1f8481b.png)

![Screenshot K](https://user-images.githubusercontent.com/27423064/227776603-2871e6b5-170b-4a80-b125-abd7dfb490b3.png)

![Screenshot L](https://user-images.githubusercontent.com/27423064/227776611-39f4c32d-7f46-4ab2-8cc2-e6ca8f14b776.png)

**Comment by ShivanKaul** [comment]
@DesertBear is this still happening?
